### ISSUE TITLE
China output fails at d3.makefile topography

### ISSUE THREAD

**Issue by hugolpz** [WikimapsAtlas/WikimapsAtlas-generator#17]
When running : 
```bash
make -f master.makefile ISO2=CN SOV3=CH1 NAME=China WEST=70.58 SOUTH=16.44 EAST=137.83 NORTH=55.33
```

I eventually get : 

```bash
WIDTH=1280 node topographic.node.js		# see inside this file for parameters' calls
Topo map, projected: Tue May 02 2017 01:19:14 GMT+0200 (CEST)
[Mon, 01 May 2017 23:19:14 GMT] "GET /output/China/administrative.topo.json" "node-XMLHttpRequest"
[Mon, 01 May 2017 23:19:14 GMT] "GET /output/China/color.jpg.b64" "node-XMLHttpRequest"
[Mon, 01 May 2017 23:19:14 GMT] "GET /output/China/trans.png.b64" "node-XMLHttpRequest"
[Mon, 01 May 2017 23:19:14 GMT] "GET /output/China/waters.topo.json" "node-XMLHttpRequest"
[Mon, 01 May 2017 23:19:14 GMT] "GET /output/China/elevations.topo.json" "node-XMLHttpRequest"

file:///home/cri-ninja/yug/make-modules/js/d3.v3.min.js:3
else for(;(u=n+r*++a)<t;)i.push(u/o);return i},vo.map=function(n){var t=new u;if(n instanceof u)n.forEach(function(n,e){t.set(n,e)});else for(var e in n)t.set(e,n[e]);return t},r(u,{has:function(n){return To+n in this},get:function(n){return this[To+n]},set:function(n,t){return this[To+n]=t},remove:function(n){return n=To+n,n in this&&delete this[n]},keys:function(){var n=[];return this.forEach(function(t){n.push(t)}),n},values:function(){var n=[];return this.forEach(function(t,e){n.push(e)}),n},entries:function(){var n=[];return this.forEach(function(t,e){n.push({key:t,value:e})}),n},forEach:function(n){for(var t in this)t.charCodeAt(0)===zo&&n.call(this,t.substring(1),this[t])}});var To="\0",zo=To.charCodeAt(0);vo.nest=function(){function n(t,a,c){if(c>=o.length)return r?r.call(i,a):e?a.sort(e):a;for(var l,s,f,h,g=-1,p=a.length,d=o[c++],v=new u;++g<p;)(h=v.get(l=d(s=a[g])))?h.push(s):v.set(l,[s]);return t?(s=t(),f=function(e,r){s.set(e,n(t,r,c))}):
TypeError: Cannot read property 'length' of undefined
    at e (file:///home/cri-ninja/yug/make-modules/js/d3.v3.min.js:3:5691)
    at Array.Oo.data (file:///home/cri-ninja/yug/make-modules/js/d3.v3.min.js:3:6504)
    at drawElevations (file:///home/cri-ninja/yug/make-modules/js/wikiatlas.js:583:4)
    at drawElevations (file:///home/cri-ninja/yug/make-modules/js/wikiatlas.js:597:4)
    at makeMap (file:///home/cri-ninja/yug/make-modules/js/wikiatlas.js:797:3)
    at o (file:///home/cri-ninja/yug/make-modules/js/queue.min.js:1:271)
    at file:///home/cri-ninja/yug/make-modules/js/queue.min.js:1:227
    at Object.<anonymous> (file:///home/cri-ninja/yug/make-modules/js/d3.v3.min.js:1:9443)
    at Object.t (file:///home/cri-ninja/yug/make-modules/js/d3.v3.min.js:1:617)
    at u (file:///home/cri-ninja/yug/make-modules/js/d3.v3.min.js:1:8305)
d3.makefile:17: recipe for target 'topographic' failed
make[1]: *** [topographic] Error 1
make[1]: Leaving directory '/home/cri-ninja/yug/make-modules/09_d3'
master.makefile:43: recipe for target 'd3' failed
make: *** [d3] Error 2
```

Key part seems : 
```
    at drawElevations (file:///home/cri-ninja/yug/make-modules/js/wikiatlas.js:583:4)
    at drawElevations (file:///home/cri-ninja/yug/make-modules/js/wikiatlas.js:597:4)
    at makeMap (file:///home/cri-ninja/yug/make-modules/js/wikiatlas.js:797:3)
```

**Comment by hugolpz** [comment]
2020 sprint.
China tested.
No bug.
